services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/certificate.pem:/etc/nginx/ssl/cert.pem
      - ./backend/private_key.pem:/etc/nginx/ssl/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - small-media
    restart: always
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - small-media
    volumes:
      - mongodb_data:/data/db
    restart: always
  
  backend:
    build: ./backend
    networks:
      - small-media
    container_name: backend
    volumes:
      - ./backend/:/backend
    env_file: .env
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    networks:
      - small-media
    container_name: react-frontend
    volumes:
      - ./client/:/client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  jupyter:
    build: ./code-explore
    volumes:
      - ./backend:/code-explore/backend
    ports:
      - "8888:8888"
    networks:
      - small-media
    container_name: explore-notebook
    depends_on:
      - backend
      - mongodb
    profiles:
      - explore
    env_file: .env
  
networks:
  small-media:
    driver: bridge

volumes:
  mongodb_data:
    external: true