version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - art-hound
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    networks:
      - art-hound
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
networks:
  art-hound:
    driver: bridge