version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - art-hound
    volumes:
      - mongodb_data:/data/db
    restart: always
  
  backend:
    build: ./backend
    networks:
      - art-hound
    container_name: backend
    env_file: .env
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    networks:
      - art-hound
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  jupyter:
    build: ./code-explore
    volumes:
      - ./backend:/code-explore/backend
    ports:
      - "8888:8888"
    networks:
      - art-hound
    container_name: explore-notebook
    depends_on:
      - backend
      - mongodb
    profiles:
      - explore
    env_file: .env
  
networks:
  art-hound:
    driver: bridge

volumes:
  mongodb_data:
    external: true